version: '3.7'

services:
  backend:
    image: node:11.12
    init: true
    environment:
    - POSTGRES_URL=postgres://graphql:backend@postgres:5432/${PROJECT_NAME}
    ports:
    - 3000:3000
    working_dir: /var/app
    volumes:
    - .:/var/app
    # For blossom development only! If this goes to a template. This **should not**
    # be included as a part of it. Instead, it should rely on the versioned package.
    - ${BLOSSOM_DEV_PATH}:/blossom
    depends_on:
    - postgres

  postgres:
    image: postgres:11.2
    environment:
    - POSTGRES_USER=graphql
    - POSTGRES_PASSWORD=backend
    - POSTGRES_DB=${PROJECT_NAME}
    ports:
    - 5433:5432
    volumes:
    - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
    name: ${PROJECT_NAME}-pgdata
    external: true
